# Generated by Django 5.2.3 on 2026-06-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('workload', 'Workload forecast'), ('carbon', 'Carbon forecast'), ('infrastructure', 'Infrastructure')], max_length=32)),
                ('source_name', models.CharField(max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('MF', 'Mainframe'), ('PR', 'Private Cloud'), ('PU', 'Public Cloud')], max_length=2)),
                ('region', models.CharField(max_length=64)),
                ('security_rating', models.PositiveSmallIntegerField(default=3)),
                ('reliability', models.FloatField(default=0.99)),
                ('power_kw', models.FloatField()),
                ('pue', models.FloatField(default=1)),
                ('capacity_cpu', models.FloatField()),
                ('capacity_memory_gb', models.FloatField()),
                ('cost_per_compute_hour', models.FloatField()),
                ('enabled', models.BooleanField(default=True)),
                ('instance_types', models.JSONField(default=dict)),
                ('raw_payload', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('strategy', models.CharField(choices=[('balanced', 'Balanced'), ('cost', 'Minimize Cost'), ('carbon', 'Minimize Carbon'), ('sla', 'SLA First')], default='balanced', max_length=32)),
                ('forecast_horizon_hours', models.PositiveSmallIntegerField(default=24)),
                ('deadline_hours', models.FloatField(default=72)),
                ('cost_target', models.FloatField(default=800)),
                ('carbon_target_g', models.FloatField(default=100000)),
                ('risk_target', models.FloatField(default=20)),
                ('cost_weight', models.FloatField(default=1)),
                ('carbon_weight', models.FloatField(default=1)),
                ('risk_weight', models.FloatField(default=1)),
                ('regional_carbon_caps', models.JSONField(default=dict)),
                ('administrator_config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarbonForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region_code', models.CharField(max_length=64)),
                ('region_label', models.CharField(max_length=160)),
                ('forecast_timestamp', models.DateTimeField()),
                ('horizon_hours', models.PositiveSmallIntegerField()),
                ('intensity_gco2_kwh', models.FloatField()),
                ('model_name', models.CharField(blank=True, max_length=160)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('renewable_availability', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_rows', to='core.dataimport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('optimal', 'Optimal'), ('feasible', 'Feasible'), ('infeasible', 'Infeasible'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('solver', models.CharField(default='Gurobi', max_length=64)),
                ('objective_value', models.FloatField(blank=True, null=True)),
                ('mip_gap', models.FloatField(blank=True, null=True)),
                ('solve_seconds', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('total_carbon_g', models.FloatField(blank=True, null=True)),
                ('total_risk', models.FloatField(blank=True, null=True)),
                ('workload_count', models.PositiveIntegerField(default=0)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.scenario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkloadForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=160)),
                ('archetype', models.CharField(blank=True, max_length=160)),
                ('compute_size', models.FloatField(help_text='Baseline cs parameter')),
                ('memory_gb', models.FloatField()),
                ('bandwidth_gbps', models.FloatField(blank=True, null=True)),
                ('bandwidth_source', models.CharField(default='provided', max_length=32)),
                ('max_parallelism', models.PositiveIntegerField(default=1)),
                ('security_level', models.PositiveSmallIntegerField(default=1)),
                ('interruptible', models.BooleanField(default=False)),
                ('specialty_processor', models.BooleanField(default=False)),
                ('data_gravity', models.BooleanField(default=False)),
                ('data_gravity_size_gb', models.FloatField(default=0)),
                ('required_reliability', models.FloatField(default=0.95)),
                ('affinity', models.CharField(default='ANY', max_length=16)),
                ('predecessors', models.JSONField(default=list)),
                ('forecast_job_arrivals', models.PositiveIntegerField(default=0)),
                ('forecast_timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='core.dataimport')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.FloatField()),
                ('duration_hours', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('pricing_mode', models.CharField(blank=True, max_length=32)),
                ('cost', models.FloatField(default=0)),
                ('carbon_g', models.FloatField(default=0)),
                ('risk', models.FloatField(default=0)),
                ('constraint_notes', models.JSONField(default=list)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.infrastructureenvironment')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='core.optimizationrun')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workloadforecast')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workloadforecast',
            constraint=models.UniqueConstraint(fields=('data_import', 'external_id'), name='unique_workload_per_import'),
        ),
    ]
