import { useEffect, useState } from "react";
import { Download } from "lucide-react";
import { Panel } from "../components/Panel";
import { api } from "../services/api";
import type { OverviewData } from "../types";

type PageType = "workloads" | "carbon" | "runs" | "placements" | "admin" | "reports" | "scenarios";

const config: Record<PageType, { title: string; subtitle: string }> = {
  workloads: { title: "Workload Forecast", subtitle: "Forecasted task characteristics generated by the baseline Azure workload pipeline." },
  carbon: { title: "Carbon Intelligence", subtitle: "Time- and region-aware carbon intensity outlook for placement decisions." },
  runs: { title: "Optimization Runs", subtitle: "Solver status, objective values, KPIs, and structured result history." },
  placements: { title: "Task Placement", subtitle: "Detailed mainframe, private cloud, and public cloud assignment decisions." },
  admin: { title: "Admin Configuration", subtitle: "Infrastructure capacity, costs, security, reliability, and environment metadata." },
  reports: { title: "Reports", subtitle: "Operational cost, emissions, SLA, utilization, and optimization summaries." },
  scenarios: { title: "Scenario Builder", subtitle: "Configure balanced, cost-first, carbon-first, and SLA-first strategies." }
};

export function DataPage({ type }: { type: PageType }) {
  const [rows, setRows] = useState<any[]>([]);
  const [overview, setOverview] = useState<OverviewData | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    const loader = type === "workloads" ? api.workloads
      : type === "carbon" ? api.carbon
      : type === "admin" ? api.environments
      : type === "scenarios" ? api.scenarios
      : api.runs;
    Promise.all([loader(), api.overview()]).then(([result, overviewData]) => {
      setOverview(overviewData);
      if (type === "placements") {
        setRows(result.flatMap((run: any) => run.placements || []));
      } else {
        setRows(result);
      }
    }).catch((err) => setError(err.message));
  }, [type]);

  const columns = rows.length ? Object.keys(rows[0]).filter((key) =>
    !["raw_payload", "input_snapshot", "result_payload", "administrator_config", "placements", "predecessors", "instance_types"].includes(key)
  ).slice(0, 8) : [];

  return (
    <div>
      <div className="page-title-row">
        <div>
          <h1>{config[type].title}</h1>
          <p>{config[type].subtitle}</p>
        </div>
        {["workloads", "carbon", "runs", "reports"].includes(type) && (
          <a
            className="secondary-button"
            href={api.exportUrl(type === "workloads" ? "workload" : type === "carbon" ? "carbon" : "optimization")}
            download
          >
            <Download size={17} /> Export JSON
          </a>
        )}
      </div>
      {(type === "workloads" || type === "carbon") && overview && (
        <Panel
          title="Model Performance"
          subtitle={type === "workloads"
            ? `Selected: ${Object.entries(overview.pipeline.workload.models_selected).map(([key, value]) => `${key.replace("target_", "")}: ${value}`).join(" · ")}`
            : "Current core benchmark"}
        >
          <div className="metric-grid">
            {(type === "workloads"
              ? overview.pipeline.workload.model_performance
              : overview.pipeline.carbon.model_performance
            ).slice(0, 12).map((metric, index) => (
              <div className="metric-card" key={`${metric.Model}-${metric.Signal || index}`}>
                <strong>{String(metric.Signal || metric.Model)}</strong>
                <span>{String(metric.Model)}</span>
                <small>R² {Number(metric.R2 || 0).toFixed(3)} · RMSE {Number(metric.RMSE || 0).toFixed(3)}</small>
              </div>
            ))}
          </div>
        </Panel>
      )}
      <Panel title={`${config[type].title} Data`} subtitle={`${rows.length} records`}>
        {error && <div className="alert error">{error}</div>}
        <div className="data-table-wrap">
          <table>
            <thead><tr>{columns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead>
            <tbody>
              {rows.map((row, index) => (
                <tr key={row.id || index}>
                  {columns.map((column) => <td key={column}>{typeof row[column] === "object" ? JSON.stringify(row[column]) : String(row[column] ?? "")}</td>)}
                </tr>
              ))}
            </tbody>
          </table>
          {!rows.length && !error && <div className="loading-state">No records yet. Seed the database or import forecast data.</div>}
        </div>
      </Panel>
    </div>
  );
}
